#list items from https://purpurmc.org/javadoc/org/bukkit/Material.html
silk-blocks:
  - REINFORCED_DEEPSLATE
  - BUDDING_AMETHYST
  - FROGSPAWN
  - GRASS
  - TALL_GRASS
  - FERN
  - LARGE_FERN
  - SMALL_DRIPLEAF
  - VINE
  - GLOW_LICHEN
  - DEAD_BUSH
  - CHORUS_PLANT
  - FARMLAND
  - DIRT_PATH

allowed-tools:
  - WOODEN_HOE
  - STONE_HOE
  - IRON_HOE
  - GOLDEN_HOE
  - DIAMOND_HOE
  - NETHERITE_HOE
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
  - WOODEN_SHOVEL
  - STONE_SHOVEL
  - IRON_SHOVEL
  - GOLDEN_SHOVEL
  - DIAMOND_SHOVEL
  - NETHERITE_SHOVEL
  - WOODEN_PICKAXE
  - STONE_PICKAXE
  - IRON_PICKAXE
  - GOLDEN_PICKAXE
  - DIAMOND_PICKAXE
  - NETHERITE_PICKAXE
  - SHEARS